### ISSUE TITLE
huge text for comments in .yaml files

### ISSUE THREAD

**Issue by r-erd** [Meep-Tech/obsidian-custom-file-extensions-plugin#11]
Hey, 

as suggested I'm opening an issue here. For me, when I open .yaml files that contain comments (that are of course prefaced with a `#`) they are shown in the regular (big) heading font size.

Maybe this is expected behaviour and there is no workaround for this (or its not a feature as of now) or maybe I am just having some conflicting plugins.

I didnt change the settings, but if I am not mistaken `yaml` is part of the markdown view types list per default.

There is no view type for "raw text", which is what I would need, I guess.

 See below image for what my "problem" is:

<img width="767" alt="grafik" src="https://github.com/MeepTech/obsidian-custom-file-extensions-plugin/assets/55588855/5c161dde-8c45-4d22-91d3-9165a7e49b5b">

**Comment by MeepTech** [comment]
Ah yes, so this is due to the 'views' obsidian has built in (or are added from other plugins). 
My plugin simply allows you to associate one of these views with file extensions.

With this in mind, if you look at the default settings you will notice the view type for all of the extensions is set to `markdown` (because this is the only view obsidian has that really works for full text files).

Because of all of this, your yaml files are being displayed in a markdown view. To fix this, you can try to download a plugin with a view type that works better (I use the [obsidian-code-files](https://github.com/lukasbach/obsidian-code-files) plugin myself on desktop), and let it associate the file types itself, or modify the settings to set the 'yaml' extensions to use the code view provided from the plugin. (You can also fix any conflicts from other plugins in the settings. Also you may need to use the mobile specific config if you use a plugin that only supports desktop)
All available view types are listed in the settings window to help with figuring out what you have to work with. 

![image](https://github.com/MeepTech/obsidian-custom-file-extensions-plugin/assets/54516780/8164bf76-13b4-4047-9e8e-f14aefe7ba45)

**Comment by r-erd** [comment]
Ahhh, thank you for getting back to me about this. I somehow didnt think of adding another view with another extension. But this makes perfect sense. Have a great day!

Edit: maybe you can add a hint for this in the readme, so other people have it easier :)
