### ISSUE TITLE
Non-markdown files do not appear in the list when generating a new link

### ISSUE THREAD

**Issue by roey-angel** [Meep-Tech/obsidian-custom-file-extensions-plugin#6]
This might be a core Obsidian behaviour, but while Obsidian will let you link to a non-markdown note (`[[file.txt]]`), it won't show, it in the list of files to choose from when creating a new link.

**Comment by MeepTech** [comment]
This is likely due to Obsidian's metadata detection only looking for `.md` files.
This would probably require another separate plugin to add other filetypes to the scannable types (I'm guessing it would be quite a bit of effort and so probably best for it's own separate project), or a core change to obsidian's detection methods.
